[project]
name = "advent-of-code"
version = "1"
description = "Advent of Code 2025 - year of Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elf>=1.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.7",
]
